### ISSUE TITLE
VB -> C# meta: Issues to pin down repro for

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#498]
List of VB->C# issues I've seen but haven't pinned down the cause for so I don't forget to come back to them. They were discovered when converting a 120k line VB winforms app.
I mostly have a repro availabe with a bit of work, but if someone else comes across one, just post it on here, or break it out into its own issue.

#### Winforms specific
* [x] If Me and MyBase events handled, they currently accidentally get duplicated for every other handled method in the class
* [x] In proj file `VbMyResourcesResXFileCodeGenerator` -> `ResXFileCodeGenerator`
* [x] Default Form and UserControl constructor with `InitializeComponent()` not always being added - look for DesignerGenerated attribute

#### Casts
* [x] Cast foreach target to IEnumerable to avoid "CS1579	foreach statement cannot operate on variables of type 'object' because 'object' does not contain a public instance definition for 'GetEnumerator'"
* [x] Explicit casts, e.g. corrected code was `ColorDialog1.ShowDialog((IWin32Window) sender)`
* [x] Add extra unused args to match handled signature, or add intermediate lambda to avoid "CS0123	No overload for '...' matches delegate 'EventHandler'"

#### Other
* [x] `ReDim Me.My2darray(6)` ends up trying to set the wrong dimension
* [x] Adding two enums (can be used with flags enums) enum1 + enum2
* [x] Missing empty arg lists in conditional invocations e.g. `.Tag?.GetType()?.FullName`
* [x] symbol outside converted project (but in compilation and source) renamed by case conflict resolver
* [x] Regression: Simplify else { if (){} } currently generated from vb elseif blocks
* [x] VB Nothing should be converted to `default` by default. Otherwise comparisons with struct go badly!
